### ISSUE TITLE
Add automatic snapshots of DigitalOcean volumes

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/infrastructure#100]
Use travis + python script with the do api wrapper to automate volumes backup and trigger slack alert if failed

**Comment by etienne-napoleone** [comment]
@thanhson1085 what should be the retention (in days) for a snapshot?

**Comment by etienne-napoleone** [comment]
subtask of #90

**Comment by thanhson1085** [comment]
Retention 10 days

**Comment by etienne-napoleone** [comment]
see https://github.com/tomochain/goutte

**Comment by etienne-napoleone** [comment]
done in https://github.com/tomochain/backups
