### ISSUE TITLE
TomoMaster Logs Format

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#105]
Log message examples:
`INFO: Update signers after sleeping 10 seconds`
`INFO: 0xf99805B536609cC03AcBB2604dFaC11E9E54a448 sign block 231026 with tx 0x8f986c4a5d444ae61e9f580087b9d97db84fa5f764f586a5c3beecc03c0cf9b9` 

So we should extract log level (INFO, DEBUG, WARN, ERROR ...) from the message

**Comment by etienne-napoleone** [comment]
Yep will to :+1:

**Comment by etienne-napoleone** [comment]
I don't see the log level on them messages from the crawler for example:
![screenshot from 2018-12-08 11-39-43](https://user-images.githubusercontent.com/26155267/49682001-19f57300-fade-11e8-8b84-16588d84572d.png)
Same for TomoScan.
Please update the logging on both TomoMaster and TomoScan to include log level

**Comment by etienne-napoleone** [comment]
Ah ok seems like it was updated in new versions

**Comment by thanhson1085** [comment]
yep, it is available in v1.0.3 TomoMaster, TomoScan does not have it yet.
Yep, So we should have `severity` logs for all projects

**Comment by etienne-napoleone** [comment]
already implemented in v1.0.3
