### ISSUE TITLE
Blockchain proxy is unstable

### ISSUE THREAD

**Issue by khaihkd** [tomochain/infrastructure#114]
`WEB3_URI: http://blockchain-proxy:8545`
 `WEB3_WS_URI: ws://blockchain-proxy:8546`
When I try connect to `rpc` (`https://rpc.tomochain.com`) from local everything is working ok. 

But inside tomoscan-crawl container is not OK
 - when I try connect to `http://blockchain-proxy:8545` sometimes has so many error 502 (`Invalid JSON RPC response`)
 - when I try connect to  `https://rpc.tomochain.com` it is very slow (slow more than 8-10 times)

**Comment by etienne-napoleone** [comment]
- What is the invalid response? Might need to tweak nginx configuration.
- Yes it's normal as one is local and one is accessed through WAN

**Comment by khaihkd** [comment]
> * What is the invalid response? Might need to tweak nginx configuration.

Invalid response is abount library cannot connect to `RPC`

> * Yes it's normal as one is local and one is accessed through WAN

But insite container if I connect via WAN, the response is very slowly

**Comment by etienne-napoleone** [comment]
should fix the issue https://github.com/tomochain/infrastructure/commit/6757ff3e5232b567ab8ed309ed19084e008b40ac
