### ISSUE TITLE
Wake Testnet up

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#118]
We will setup a new testnet (reset all data)
So we need to prepare for Testnet infrastructure.
- Tmn
- Move to DO
- change RPC/WS endpoint, eg: https://rpc.testnet.tomochain.com

Before deploy new testnet, we need to finish:
- New genesis block
- Custom consensus: https://github.com/tomochain/tomochain/issues/351
- Announce to community

**Comment by etienne-napoleone** [comment]
New consensus, yay!
Yep will be based on current devnet and mainnet regarding urls and infra :+1:

**Comment by thanhson1085** [comment]
After discussed, we will keep the old endpoints and do not move to DO

**Comment by etienne-napoleone** [comment]
Done, but some error making the chain stop in a 3 nodes setup are being investigated in https://github.com/tomochain/tomochain/issues/391
