### ISSUE TITLE
Add fullnode for tomoscan

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/infrastructure#119]
To upgrade crawler performances, should have a fullnode dedicated to him
16cpu/32GB

**Comment by etienne-napoleone** [comment]
Changes merged, deploying the machine

**Comment by etienne-napoleone** [comment]
Machine deployed. Need to prepare update of TomoScan to use `fullnode_tomoscan01:8545` and `fullnode_tomoscan01:8546` instead of the internal blockchain proxy @khaihkd or @thanhson1085

**Comment by khaihkd** [comment]
need `ws` too

**Comment by thanhson1085** [comment]
I updated tomoscan. but forgot create PR, but you can take a look: https://github.com/tomochain/infrastructure/commit/a2e74e912209422c9091878628a3f971b93d4eb8 @etienne-napoleone

**Comment by etienne-napoleone** [comment]
Ah thanks @thanhson1085 , actually I could have done it, I tought this conf was in the tomoscan repo like in TomoMaster. Thanks!

**Comment by etienne-napoleone** [comment]
using fullnode in prod
