### ISSUE TITLE
Increase RPC resiliency

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#139]
After investigate our RPC endpoint issue. I propose some changes as below:

- Using Nginx before MNs
- Remove LB DO
- Move 2 MNs to AWS 
- If DO issue, rpc.tomochain.com can automatically switch to MNs on AWS

**Comment by etienne-napoleone** [comment]
Yep, good idea, I'd like to propose based on your idea:
- cloudflare loadbalance `rpc` to `rpc01`, `rpc02`, etc.
- each rpc endpoint is a provider + region combo with X nodes
- each rpc endpoint is served and ssl terminated by an http server like you said. let's get rid of SaaS LBs for now

**Comment by thanhson1085** [comment]
cloudflare loadbalance? you meant this service https://www.cloudflare.com/load-balancing/, right?

**Comment by etienne-napoleone** [comment]
yes, I think using cloudflare for LB the main domaine to each endpoints has this advantages:
- if there is an outage in a datacenter, we don't have to worry about the main loadbalancer being unavailable
- we can also add some geographical optimisations (for ex: traffic from the US would be served to AWS in the US, not DO in SGP)

**Comment by etienne-napoleone** [comment]
Another more simple solution would be to have rpc01, rpc02, etc
Juste create a CNAME rpc -> rpc02
And if one fail manually edit the CNAME. As it's proxied by cloudflare, it should be instant (no DNS propagation)
Not automatic tho

**Comment by thanhson1085** [comment]
Agree. We can active LB service in CF.

We also need a internal proxy (nginx) before the nodes, because of some pros:
- handle ssl
- add some metrics for monitor, e.g: response_time, status_code for API from the nodes

**Comment by etienne-napoleone** [comment]
Yep, I think we can do it like this:
```
+-The internet----+-Cloudflare---------------+-Provider(DO,AWS,etc)-----------------------+
|                 |                          |                                            |
|                 |     (https://rpc...)     |  (https://rpcXX...)     (http://mn04:8545) |
|    client       |     DNS load balancer    |    SSL + HTTP LB          masternode RPC   |
|      |          |            |             |         |                       |          |
|      +-request-------------->+             |         |                       |          |
|      |          |            |             |         |                       |          |
|      |          |            +---------------------->+                       |          |
|      |          |            |             |         |                       |          |
|      |          |            |             |         +---------------------->+          |
|      |          |            |             |         |                       |          |
|      |          |            |             |         +<-------------response-+          |
|      |          |            |             |         |                       |          |
|      |          |            +<----------------------+                       |          |
|      |          |            |             |         |                       |          |
|      +<----------------------+             |         |                       |          |
|      |          |            |             |         |                       |          |
|      +          |            +             |         +                       +          |
|                 |                          |                                            |
+-----------------+--------------------------+--------------------------------------------+
```

**Comment by thanhson1085** [comment]
yep, nice pic :)

**Comment by etienne-napoleone** [comment]
Shall we have for example:
DO: SGP
AWS: US
So we can also optimize traffic latency?

**Comment by thanhson1085** [comment]
Agree, DO in SGP, AWS in US

**Comment by etienne-napoleone** [comment]
@thanhson1085 
Could you confirm me that we go with those fullnodes:
- 2x DO SGP
- 2x AWS NYC

?

**Comment by thanhson1085** [comment]
3x DO SGP
2x AWS NYC

I will run some tests with fullnode first. If OK, then you can add fullnode later

**Comment by etienne-napoleone** [comment]
rpc.tomochain is now lb'd between DO in SGP1 (tomochain01-03) and on AWS in the US (tomochain04-05)
Next:
- Take care of websocket too
- check if we should remove LB'cing in SGP1 DO and have per node https and ssl termination

**Comment by etienne-napoleone** [comment]
websocket done in https://github.com/tomochain/infrastructure/commit/50ba92a2c5ddb55d69b98f169bca863a0e39575c
Concerning per node SSL termination in DO SGP1, will be included later when infra is reworked
