### ISSUE TITLE
Refactor tomomaster container

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/infrastructure#38]
Check how to run crawler and server:
- same container with honcho?
- two containers?

Refactor the build process

**Comment by thanhson1085** [comment]
I suggest `same container with honcho`

And we should move `npm run build` to base image (dockerfile in tomomaster)

**Comment by thanhson1085** [comment]
```
truffle migrate --compile-all --reset development

mv TomoValidator.json build/contracts/TomoValidator.json
mv TomoRandomize.json build/contracts/TomoRandomize.json
mv BlockSigner.json build/contracts/BlockSigner.json
```

We can remove line `truffle migrate --compile-all --reset development`

It seems that we lack file Migrations.json

Do you think we should locate all json file in `tomomaster` repo?

**Comment by thanhson1085** [comment]
Now, I put all json files required for the deployment here https://github.com/tomochain/tomomaster/tree/master/abis

**Comment by etienne-napoleone** [comment]
Cool thanks, I'll try to update the image soon!

**Comment by thanhson1085** [comment]
And take a look my comments at https://github.com/tomochain/tomomaster/issues/135
