### ISSUE TITLE
mount volume for Redis's data

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#67]
TomoScan and TomoMaster use Redis to store cache data and jobs
We need to make redis's data persistent

**Comment by etienne-napoleone** [comment]
Will do.
Also be aware that a snapshot is written to disk every X time.
If you want perfect persistency and ensure no data loss (I don't know if it's a requirement or not), please read http://redis.io/topics/persistence .

**Comment by thanhson1085** [comment]
I know, so I request your mount `/data' volume for Redis Docker container
