### ISSUE TITLE
Centralized logs

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#72]
It is right time to implement centralized logs for our system.

It will be help us to improve:
- do not lose the logs after restarting containers
- easy to query logs from web view

So we should create a new server to store the logs, and implement logs stacks for both devnet, testnet

**Comment by thanhson1085** [comment]
As discussed with @ngtuna , We also need to enable collecting the node logs for `tmn`, It should be an option when user start a node `tmn start`, default value is `true` https://github.com/tomochain/tmn/issues/39

**Comment by etienne-napoleone** [comment]
ok! Keep in mind that logs that are forwarded are not available anymore through `docker logs`

**Comment by etienne-napoleone** [comment]
deployed in devnet. will test stability for some time and then deploy to testnet and use in mainnet

**Comment by etienne-napoleone** [comment]
Ok. Deployed in mainnet too
