### ISSUE TITLE
RPC Load balance

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#73]
We should setup load balance for RPC request (eg. testnet is https://testnet.tomochain.com)
For the testnet, we can do roud-robin load balance for RPC to Sun, Moon, Earth
It will be a good function to prepare for the mainnet
We can use Nginx Load Balance, we also need to research to use AWS Load Balance

**Comment by thanhson1085** [comment]
Switch to Traefik will take more time. I just expect use nginx `upstream` to do the load balance

**Comment by etienne-napoleone** [comment]
Ok, will switch to traefik later

**Comment by etienne-napoleone** [comment]
implemented externaly with DO Load balancer (endoint rpc. and ws.) and internally with #94
