### ISSUE TITLE
Plan for mainnet infastructure

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#76]
Infrastructure need to be ready before 10th Dec, this year. This is the most important job we need to be done in the end of this year.

Mannet:
- prepare infrastructure source code (genesis, bootnodes, images, docker-stack, ...)
- setup 3 Masternodes, 1 nginx proxy loadbalance to 3 endpoint
- TomoScan, TomoMastser, stats, 1 nginx proxy
- setup domains
- make `tmn` ready

We need to think and plan and make this done @etienne-napoleone

**Comment by etienne-napoleone** [comment]
duplicates #77
