### ISSUE TITLE
Plan infrastructure for mainnet

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#77]
From technical side, for the mainnet, everything need to be done before 30 Nov, this year.

Mainnet Infrastructure includes: 

- [x] Prepare Infrastructure source code (genesis, bootnode, docker-stack)
- [x] 5 masternodes, 1 nginx RPC proxy
- [x] TomoMaster, TomoScan, Stats, 1 nginx proxy
- [x] Domain, https
- [x] make `tmn` ready

This is the most important jobs, we need to think, plan to make it well done @etienne-napoleone .

**Comment by etienne-napoleone** [comment]
Infrastructure is deployed. Need to fine tune it now
