### ISSUE TITLE
Prepare machines for mainnet 

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/infrastructure#82]
Create the machines on AWS and create the different swarms

**Comment by etienne-napoleone** [comment]
Proposition for mainnet machines: (@thanhson1085)

## Main Swarm:
- 3x manager (1 vCPU, 1GB RAM)
- 3x worker masternode (8 vCPU, 32GB RAM)
- 1x worker netstats (2 vCPU, 2GB RAM)
- 1x worker tomomaster (8 vCPU, 32GB RAM)
- 1x worker tomoscan (8 vCPU, 32GB RAM)

## Metrics Swarm:
- 3x manager (1 vCPU, 1GB RAM)
- 1x worker metrics (4vCPU, 8GB RAM)
- 1x worker logging (4vCPU, 8GB RAM)

## DO Load balancers
- 1x RPC endpoint (https://mainnet.tomochain.com)
- 1x WS endpoint (https://ws.mainnet.tomochain.com)
- 1x netstats endpoint (https://stats.tomochain.com)
- 1x tomomaster endpoint (https://master.tomochain.com)
- 1x tomoscan endpoint (https://scan.tomochain.com)
- (1x grafana endpoint (https://grafana.tomochain.com))
- (1x graylog endpoint (https://graylog.tomochain.com))

(Maybe the grafana and graylog endpoints can just be a nginx proxy)

**Comment by thanhson1085** [comment]
For WS endpoint, I would like to keep wss://mainnet.tomochain.com/ws (same Devnet, Testnet, and Infura)

**Comment by thanhson1085** [comment]
We run 5 masternodes for Mainnet. So it should be:
`5x worker masternode (8 vCPU, 32GB RAM)`

**Comment by etienne-napoleone** [comment]
Are they all using directly the Docker images? Or 2 of them use tmn?

**Comment by thanhson1085** [comment]
directly the Docker images, it will be more easy to mange and implement (same 3-first masternodes0

**Comment by etienne-napoleone** [comment]
ah, does the bootnodes requires a separate machine? @thanhson1085 @ngtuna
Or should we just serve 3 of them on the 3 main main masternode machines?

**Comment by thanhson1085** [comment]
Bootnodes do not require much resources. 3 bootnodes can run on masternodes's machines

**Comment by etienne-napoleone** [comment]
Machines are created
