### ISSUE TITLE
TomoMaster Crawler should internally connect to the node

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#89]
https://github.com/tomochain/infrastructure/blob/f2d091b0e839d2a6641afd2545e0301f5772dfd1/networks/devnet/main/04tomomaster.yml#L26

It could be easy if they are running in a same swarm. 

Also take a look for TomoScan crawlers

**Comment by etienne-napoleone** [comment]
So we have two choice:
- load balanced external access
- single node swarm access
One have a bit more latency, the other one have load balancing and redundancy

**Comment by thanhson1085** [comment]
I am thinking about this idea.
We have external loadbalances (cloudflare, cloud provider aws, DO).
We will also setup a internal load-balance (nginx upstream). So the follow will be: the crawler -> internal loadbalance -> nodes

**Comment by etienne-napoleone** [comment]
yep can do!

**Comment by etienne-napoleone** [comment]
implemented in #94
