### ISSUE TITLE
Healthcheck, Backup and Alerts for the nodes

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/infrastructure#90]
We will run 5 masternodes in mainnet, running a secure and stable blockchain network is the most important tasks for us. Let discuss about Healthcheck, Alerts and Backup.

### Alerts:
When: 
- the node does not create a new block after 2 minutes
- `tomo` process is not running (bypass it if we run the node in a docker container)
Should do:
- send an alert to our Slack `alerts` channel

How to implement:
There are many way to implement it, let discuss to chose the good one at the right time (e.g: Bash script, docker, grafana, graylogs, kapacitor ...)

### Healthcheck:
When:  
- the node does not create a new block after 2 minutes
Should do:
- Restart the node

How to implement:
There are many way to implement it, let discuss to chose the good one at the right time. Bash Script is a temporary way to implement. But I think the good way is use the monitor tools (grafana, kapacitor, graylogs) to check `When`, and `Do` trigger a jobs in Travis-CI to restart the node.

### Backup:
When:
- Daily

Backup what:
- The compressed `chaindata` directory (ignore keystores)

Backup to: S3

How to implement:
Cron-job  is OK.
But I like to use scheduled Travis-CI jobs for this task. We should create a Github repository to implement all backup tasks (not only the nodes, but also TomoScan, TomoMaster ...).
We also need to publish the links so that user is able to download the backup data. I think we can use `gh-pages`
The backup flow: Trigger a Travis-CI job -> ssh to server -> run the backup to S3 -> update `gh-pages` -> done

**Comment by etienne-napoleone** [comment]
Concerning the alerting, with graylog (see #87 ) it's really easy to monitor block creation and in general anything that is appearing in the logs.

**Comment by etienne-napoleone** [comment]
@thanhson1085 
![image](https://user-images.githubusercontent.com/26155267/48476258-27964080-e831-11e8-9075-fa6b4229282a.png)
For backuping the chaindata, I think the easiest way would be to store the blockchain data of one of the node (let's say sun) on the block storage by mounting it on `/var/lib/docker/volumes/[volume_name]/_data` and scheduling snapshots every days

**Comment by thanhson1085** [comment]
DO backup is OK.
We do the backup for 2 purposes, 1 for us to fast restore the node, 2 for user who want to start from chaindata backup.

**Comment by etienne-napoleone** [comment]
so, I ended up using the rexray plugin to directly use DO volumes. It takes care of attaching the DO volume to the droplet, mountinf on the fs and use it as docker volume for the container.
```bash
$ docker plugin install rexray/dobs DOBS_REGION=$REGION DOBS_TOKEN=$TOKEN
[...]
$ docker volume ls
DRIVER               VOLUME NAME
rexray/dobs:latest   sgp1-vol-mainnet-grafana-db
rexray/dobs:latest   sgp1-vol-mainnet-grafana-influx
rexray/dobs:latest   sgp1-vol-mainnet-graylog-db
rexray/dobs:latest   sgp1-vol-mainnet-graylog-es
rexray/dobs:latest   sgp1-vol-mainnet-graylog-journal
rexray/dobs:latest   sgp1-vol-mainnet-masternode01-chaindata
rexray/dobs:latest   sgp1-vol-mainnet-masternode02-chaindata
rexray/dobs:latest   sgp1-vol-mainnet-masternode03-chaindata
rexray/dobs:latest   sgp1-vol-mainnet-tomomaster-db
rexray/dobs:latest   sgp1-vol-mainnet-tomoscan-db
```
You can then use it with your service like:
```yml
# [...]
  tomoscan_db:
    image: mongo:3.6
    volumes:
      - sgp1-vol-mainnet-tomoscan-db:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.project == tomoscan

volumes:
  sgp1-vol-mainnet-tomoscan-db:
    external: true
```

**Comment by etienne-napoleone** [comment]
To make the chaindata available, we can easily do it this way:
- create new volume based on latest snapshot of `sgp1-vol-mainnet-masternode01-chaindata`
- mount it in a new container that serves it (via https for ex.)

**Comment by thanhson1085** [comment]
Yep, look good.
How about users who do not use DO? Can they download the backup?

**Comment by etienne-napoleone** [comment]
Yep, with steps 2 and 3, could `wget https://snapshot.tomochain.com -o snapshot.tag.gz`
(example)

**Comment by thanhson1085** [comment]
OK, clear

**Comment by etienne-napoleone** [comment]
Current state:
- [x] Alerts
- [x] Backups (manual)
- [ ] Automated
- [ ] Healthcheck

**Comment by etienne-napoleone** [comment]
Current state:
- [x] Alerts
- [x] Backups (manual)
- [x] Backups (automated)
- [ ] Healthcheck

**Comment by etienne-napoleone** [comment]
will implement healthcheck case by case if needed. For now we have a pretty good "crash if failing" workflow
